### ISSUE TITLE
Website Wordpress?

### ISSUE THREAD

**Issue by n3str1x** [sifex/AAF-Website#68]
Hello, how are you?
I love your project, but I tried to use it and I could not. I got error in the styles and it was all disorganized.
My question is if this is a site for wordpress?
This erro: http://bit.ly/2o0QvkN

**Comment by sifex** [comment]
Ah ok, I need to fix this as it's not meant for others to go through it.

-- 
Alex Sinnott

**Comment by n3str1x** [comment]
Sorry for my bad english, using google translate, thanks u for best project.

**Comment by n3str1x** [comment]
have updated?

**Comment by sifex** [comment]
This project is not going to be fixed for others development. 

If you wish to copy this work, please research how Apache Includes work.

If you would like to change anything on the website, please submit a separate Github Issue.

**Comment by dcousens** [comment]
@n3str1x it appears you are missing: `<link rel="stylesheet" href="/aaf-global/styles/aaf-global.css">` on your page.

**Comment by sifex** [comment]
@dcousens It's included in ```/aaf-global/includes/global-styles.inc```
